### ISSUE TITLE
Proxying to HTTPS backend

### ISSUE THREAD

**Issue by pauldub** [heroku/vegur#174]
Hello, 

I am wondering how one would proxy a request to an HTTPS backend. This is not listed in the `Not Supported` section of the README and it looks like `:vegur_client` could handle it but has a hard-coded `ranch_tcp` transport. But I could not find a way to make it work, is it possible?

**Comment by ferd** [comment]
I think that you're right and right now it isn't supported. It should however be possible to expand the returned values for the back-end services to be more than `{Ip, Port}` and possibly include `{Transport, IP, Port}` so that https://github.com/heroku/vegur/blob/master/src/vegur_proxy.erl#L97-L107 can pattern match on it. But right now it would require patching to work.

**Comment by pauldub** [comment]
Ok, thank you for answering. My use case is building a tool similar to runscope and my targets are listening only on HTTPS. I will play a little bit with a patch and open a PR if you are interested.

**Comment by ferd** [comment]
I'm personally no longer a maintainer on this since I moved out of Heroku, but I am personally interested in keeping up with the project. For mergeability of patches, I'm pining @joedevivo and @ypaq there.
