### ISSUE TITLE
How does vegur know this is a valid request?

### ISSUE THREAD

**Issue by geeknik** [heroku/vegur#182]
While bug bounty hunting, I came across a host running vegur that responded to malformed GET requests with 200 OK and I'm curious how vegur knows that is a valid request and where to route it? I read the [wiki page](https://devcenter.heroku.com/articles/http-routing) where it says `The Heroku HTTP stack supports any HTTP method (sometimes called a “verb”), even those not defined in an RFC, except the following: CONNECT.` but it didn't go into detail about how it knows what to do with any HTTP method. Thank you.

Request
```
\xC9\xA2\xE1\xB4\x87\xE1\xB4\x9B / HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Accept: */*
Connection: keep-alive
Host: hostname
```

Response
```
HTTP/1.1 200 OK
Connection: close
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Sun, 20 Dec 2020 19:33:32 GMT
Server: Apache
Via: 1.1 vegur
```

**Comment by ferd** [comment]
Vegur does not "parse" the method past looking for delimiters. It will use any characters accepted in there and pass them through to another server as-is.

The RFC7230 spec allows the following (https://tools.ietf.org/html/rfc7230#section-3.2.6 and https://tools.ietf.org/html/rfc5234#appendix-B.1):

```
   Most HTTP header field values are defined using common syntax
   components (token, quoted-string, and comment) separated by
   whitespace or specific delimiting characters.  Delimiters are chosen
   from the set of US-ASCII visual characters not allowed in a token
   (DQUOTE and "(),/:;<=>?@[\]{}").

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

      DIGIT          =  %x30-39             ; 0-9
      ALPHA          =  %x41-5A / %x61-7A   ; A-Z / a-z
      VCHAR          =  %x21-7E             ; visible (printing) characters
```

Strictly speaking, it seems like the proxy itself allows a broader set of characters as what would otherwise be accepted in the strictest of server. That being said, there is no way to wedge an HTTP request in there that would be a risk of injection or most security threats I know on (the delimiter would be hit early if not the line length limit), and the proxy is written in a memory-safe language that wouldn't be at risk of any sort of exploit issues related to this behaviour.

The only practical issues are possibly related to compatibility across servers, and the end-behaviour observed otherwise (i.e. the 200 OK you get) are the result of the server on the back-end behind Heroku's proxy responding to the original query, Apache in this case.

**NOTE**: I do not work for Heroku (Salesforce). I was one of the developers on this application years ago but do not speak for the company in any function whatsoever.

**Comment by geeknik** [comment]
Thank you that's everything i needed to hear. 👍🏻
